"""Initial migration

Revision ID: ef5a0db2ae92
Revises: 
Create Date: 2025-09-29 08:40:20.679435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5a0db2ae92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_keluar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_surat', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('penerima', sa.String(length=100), nullable=True),
    sa.Column('perihal', sa.String(length=200), nullable=True),
    sa.Column('file_scan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surat_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_surat', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('pengirim', sa.String(length=100), nullable=True),
    sa.Column('perihal', sa.String(length=200), nullable=True),
    sa.Column('file_scan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('disposisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surat_id', sa.Integer(), nullable=True),
    sa.Column('pengirim_id', sa.Integer(), nullable=True),
    sa.Column('penerima_id', sa.Integer(), nullable=True),
    sa.Column('instruksi', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['penerima_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pengirim_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['surat_id'], ['surat_masuk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disposisi')
    op.drop_table('user')
    op.drop_table('surat_masuk')
    op.drop_table('surat_keluar')
    # ### end Alembic commands ###
